'use strict';
const STORAGE_KEY='kajitori_stable_mvp_v2',V02_VERSION=2,CAPACITY_LIMIT={protect:1,normal:2,ahead:3},STATE_LABEL={enough:'十分ある',soon:'少なめ',out:'足りない'};
const TEMPLATES=[
{id:'tomorrow_plan',category:'other',priority:110,label:'明日の予定を確認',minutes:5,summary:'明日のスケジュールと持ち物をチェック',reason:'前日に予定を持つと、朝の判断を減らせます。',close:'予定・持ち物・移動の不明点を閉じた',recurrence:'daily'},
{id:'night_set',category:'child',priority:100,label:'夜用セットを準備',stateKey:'night_set',stateLabel:'夜用セット',minutes:8,summary:'オムツ・おしりふき・着替えをまとめる',reason:'寝る前にそろえておくと、夜中に探さずに済みます。',close:'夜用セットの状態を確認し、必要なら補充した',recurrence:'daily',evidence:'inventory',evidenceText:'夜用セットを切らす前に補充できた'},
{id:'daycare_bag',category:'child',priority:96,label:'次の登園セットを確認',minutes:8,summary:'バッグ・着替え・必要物の差分を確認',reason:'前日に差分を持つと、出発前の判断を減らせます。',close:'バッグ・着替え・必要物の差分を閉じた',recurrence:'daycareTomorrow',evidence:'deadline',evidenceText:'登園前に持ち物の準備を閉じた'},
{id:'diaper_stock',category:'child',priority:90,label:'オムツの在庫を確認',stateKey:'diaper_stock',stateLabel:'オムツ在庫',minutes:5,summary:'残り枚数を確認し、必要なら購入メモを作る',reason:'急に切らすと慌てるため、早めに把握しておきます。',close:'在庫を確認して、必要なら買うものをメモした',recurrence:'daily',evidence:'inventory',evidenceText:'オムツが少ない段階で気づけた'},
{id:'meal_plan',category:'house',priority:80,label:'夕食の方針を決める',minutes:8,summary:'作る・買う・残り物のどれにするか決める',reason:'夕方に残る判断を、余力のある時間へ前倒しできます。',close:'夕食の方針を決めた',recurrence:'daily'},
{id:'laundry_next',category:'house',priority:74,label:'洗濯の次工程を進める',minutes:12,summary:'洗う・干す・乾燥・戻すの次を確認',reason:'途中で止まりやすい工程を、次の一手まで閉じます。',close:'洗濯の次工程が止まっていない',recurrence:'daily'},
{id:'rest_window',category:'other',priority:65,label:'休息時間を1枠決める',minutes:5,summary:'中断されにくい時間帯をひとつ確保',reason:'家事の件数ではなく、今日の余力を守る時間も先に持ちます。',close:'休息の時間帯を1つ決めた',recurrence:'daily'},
{id:'older_ten',category:'child',priority:62,label:'上の子と2人だけの10分',minutes:10,summary:'1対1で過ごす時間をつくる',reason:'下の子対応が続く日に、1対1で過ごす時間を確保します。',close:'10分だけ一緒に過ごした',recurrence:'olderChild'},
{id:'next_size',category:'child',priority:54,label:'次のオムツサイズを確認',minutes:5,summary:'現在の様子を見て、次のサイズを検討する',reason:'月齢だけで決めず、現在の様子を確認するきっかけにします。',close:'現在の様子を見て、買うか保留を決めた',recurrence:'weeklySunday'}
];
const CATEGORY={child:{label:'育児',className:'child'},house:{label:'家事',className:'house'},other:{label:'その他',className:'other'}};
const RESPONSIBLE_LOOPS=[['オムツ・消耗品','残量に気づく → 必要量を判断 → 調達 → 収納 → 次回確認'],['食事','方針決定 → 在庫確認 → 調達 → 準備 → 片付け'],['保育園','連絡確認 → 差分判断 → 準備 → 提出 → 補充'],['洗濯','回収 → 洗う → 乾かす → 畳む → 定位置へ戻す'],['予定','情報収集 → カレンダー反映 → 準備 → 当日対応 → 次回設定']];
let rootState=loadRootState(),activeTab='today',activeFilter='all',lastUndo=null,toastTimer=null,saveFailed=false,detailTaskId=null,detailStateChoice=null,pendingSwap=null,onboardingStep=1,onboardingDraft=null,editingProfile=false;
function deepClone(v){return JSON.parse(JSON.stringify(v))}function pad(n){return String(n).padStart(2,'0')}function dateKey(d=new Date()){return d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate())}function dateFromKey(k){return new Date(k+'T12:00:00')}function addDays(k,n){const d=dateFromKey(k);d.setDate(d.getDate()+n);return dateKey(d)}function today(){return dateKey(new Date())}function nowIso(){return new Date().toISOString()}function dayOfWeek(k){return dateFromKey(k).getDay()}function isWeekday(k){const d=dayOfWeek(k);return d>=1&&d<=5}function formatShortDate(k){if(!k)return'未確認';const d=dateFromKey(k);return(d.getMonth()+1)+'/'+d.getDate()}function templateById(id){return TEMPLATES.find(t=>t.id===id)}function esc(v){return String(v??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]))}
function freshV02(){return{version:V02_VERSION,profile:{initialized:false,babyBirthdate:'',olderChild:false,daycare:false,feeding:'mixed',leaveEnd:'',rhythm:'all_day'},days:{},stateFacts:{},questionHistory:[],questionCooldownUntil:{},questionKnowStreak:{},evidenceEvents:[],spontaneous:[]}}function freshDay(){return{capacity:'normal',restOnly:false,planIds:[],status:{},currentId:null,questionKey:null,questionAnswered:false}}
function loadRootState(){let root=null;try{const raw=localStorage.getItem(STORAGE_KEY);if(raw){const p=JSON.parse(raw);if(p&&typeof p==='object'&&!Array.isArray(p))root=p}}catch(e){}if(!root)root={tasksByDate:{},missedLog:[],retryQueue:[]};if(!root.v02||root.v02.version!==V02_VERSION)root.v02=freshV02();normalizeV02(root.v02);return root}
function normalizeV02(v){const b=freshV02();v.profile=Object.assign(b.profile,v.profile||{});v.days=v.days||{};v.stateFacts=v.stateFacts||{};v.questionHistory=Array.isArray(v.questionHistory)?v.questionHistory:[];v.questionCooldownUntil=v.questionCooldownUntil||{};v.questionKnowStreak=v.questionKnowStreak||{};v.evidenceEvents=Array.isArray(v.evidenceEvents)?v.evidenceEvents:[];v.spontaneous=Array.isArray(v.spontaneous)?v.spontaneous:[]}
function saveRootState(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(rootState));saveFailed=false;document.getElementById('saveError')?.classList.remove('show');return true}catch(e){saveFailed=true;document.getElementById('saveError')?.classList.add('show');return false}}
function mutate(label,fn,undoable=true){const before=deepClone(rootState.v02);fn();if(!saveRootState()){rootState.v02=before;renderAll();return false}if(undoable)lastUndo={label,before};renderAll();showToast(label,undoable);return true}
function undoLast(){if(!lastUndo)return;const current=deepClone(rootState.v02),label=lastUndo.label;rootState.v02=lastUndo.before;if(!saveRootState()){rootState.v02=current;renderAll();return}lastUndo=null;renderAll();showToast(label+'を元に戻しました',false)}
function showToast(text,withUndo=false){const t=document.getElementById('toast');document.getElementById('toastText').textContent=text;document.getElementById('toastUndo').style.display=withUndo?'block':'none';t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),withUndo?5200:2600)}
function ensureTodayDay(){const v=rootState.v02,key=today();if(!v.days[key])v.days[key]=freshDay();const d=v.days[key];d.planIds=Array.isArray(d.planIds)?d.planIds:[];d.status=d.status||{};if(!d.capacity||!CAPACITY_LIMIT[d.capacity])d.capacity='normal';if(typeof d.restOnly!=='boolean')d.restOnly=false;return d}
function goalCount(d=ensureTodayDay()){return d.restOnly?0:CAPACITY_LIMIT[d.capacity]||2}function setGoal(n){n=Number(n);if(![0,1,2,3].includes(n))return;mutate('今日の量を'+n+'件にしました',()=>{const d=ensureTodayDay();d.restOnly=n===0;d.capacity=n<=1?'protect':n===2?'normal':'ahead'},false)}
function templateEligible(t,key=today()){const p=rootState.v02.profile;if(t.recurrence==='daily')return true;if(t.recurrence==='olderChild')return!!p.olderChild;if(t.recurrence==='daycareTomorrow')return!!p.daycare&&isWeekday(addDays(key,1));if(t.recurrence==='weeklySunday')return dayOfWeek(key)===0;return true}
function eligibleTasks(){return TEMPLATES.filter(t=>templateEligible(t)).sort((a,b)=>b.priority-a.priority)}
function taskStatus(id){return ensureTodayDay().status[id]||'active'}function isDone(id){const s=taskStatus(id);return s==='done'||s==='already'}
function completeTask(id,stateValue){const t=templateById(id);if(!t)return;mutate('完了を記録しました',()=>{const d=ensureTodayDay();if(!d.planIds.includes(id))d.planIds.push(id);if(t.stateKey&&stateValue){rootState.v02.stateFacts[t.stateKey]={value:stateValue,checkedDate:today(),checkedAt:nowIso()}}maybeCreateEvidence(t);d.status[id]='done';d.currentId=null});closeDetail()}
function reopenTask(id){mutate('完了を戻しました',()=>{const d=ensureTodayDay(),key=today();d.status[id]='active';rootState.v02.evidenceEvents=rootState.v02.evidenceEvents.filter(e=>!(e.date===key&&e.templateId===id))})}
function deferTask(id){mutate('あとで見るに移しました',()=>{const d=ensureTodayDay();if(!d.planIds.includes(id))d.planIds.push(id);d.status[id]='deferred'});closeDetail()}
function dismissTask(id){mutate('今日は出さないにしました',()=>{const d=ensureTodayDay();if(!d.planIds.includes(id))d.planIds.push(id);d.status[id]='dismissed'});closeDetail()}
function alreadyDoneTask(id){mutate('もう済んでいるとして記録しました',()=>{const d=ensureTodayDay();if(!d.planIds.includes(id))d.planIds.push(id);d.status[id]='already'});closeDetail()}
function maybeCreateEvidence(t){if(!t?.evidence)return;const v=rootState.v02,key=today(),id=key+'-'+t.id+'-'+t.evidence;if(v.evidenceEvents.some(e=>e.id===id))return;if(t.evidence==='inventory'){const f=v.stateFacts[t.stateKey];if(!f||f.checkedDate!==key||f.value!=='soon')return}if(t.evidence==='deadline'){const due=deadlineFor(t,key);if(!due||new Date()>=due)return}v.evidenceEvents.push({id,date:key,createdAt:nowIso(),type:t.evidence,templateId:t.id,text:t.evidenceText})}
function deadlineFor(t,key){if(t.id==='daycare_bag'&&rootState.v02.profile.daycare){const tom=addDays(key,1);if(!isWeekday(tom))return null;return new Date(tom+'T08:00:00')}return null}
function addSpontaneous(){mutate('自分で気づけたことを記録しました',()=>rootState.v02.spontaneous.push({id:'s-'+Date.now(),date:today(),createdAt:nowIso()}))}
function categoryOf(t){return CATEGORY[t.category]||CATEGORY.other}
